# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 393c88e7200f6e2575935fe77efa8961058aabf0905b25484a89de3f9704eafcef8a22389f35f85c45c2faa8fbf979b6412c6f1c4319b288fe591b812df305b1

test:
  secret_key_base: aac51384a7e657dd935c9df22d6d1512bca84cde67b1c425f955d54a08f43abaa7c88c1324d6f512ff5b9beb8f1fd64676ac585f776f2372cbfc498c881d96fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
